// Drop replacement images into public/images/home/. All image slots live here.
export const homeVisuals = {
  heroImage: '/images/home/hero.webp',
  aboutImage: '/images/home/about.webp',
  categoryFallback: '/images/home/category.webp',
  productFallback: '/images/home/product.webp',
  promoMainImage: '/images/home/promo-main.webp',
  promoSideImage1: '/images/home/promo-side-1.webp',
  promoSideImage2: '/images/home/promo-side-2.webp',
  promoGreenImage: '/images/home/promo-green.webp',
  promoBonsaiImage: '/images/home/promo-bonsai.webp',
  collectionImage: '/images/home/collection.webp',
  bannerImage: '/images/home/banner.webp',
  knowledgeImage1: '/images/home/knowledge-1.webp',
  knowledgeImage2: '/images/home/knowledge-2.webp',
  knowledgeImage3: '/images/home/knowledge-3.webp',
  ...Object.fromEntries(Array.from({length: 7}, (_, i) => [`galleryImage${i + 1}`, `/images/home/gallery-${i + 1}.webp`])),
};

// Optionally assign category/product artwork by real API ID without editing components.
export const categoryVisuals = {};
export const productVisuals = {};

// Marketplace branding overrides keyed by genuine public store ID.
export const storeVisuals = {};

// Homepage artwork. No stock photos are fetched or generated by the storefront.
export const marketplaceVisuals = {
  compactBanner: null,
  // Landscape photo with bonsai on the right. Missing photos use the existing illustration.
  heroImage: '/images/home/hero.webp',
  heroFallback: '/images/hero-bonsai.svg',
  sellerImage: null,
};
